//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFTMarketPlace.SmartContracts {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class nethereum_gen : global::System.Configuration.ApplicationSettingsBase {
        
        private static nethereum_gen defaultInstance = ((nethereum_gen)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new nethereum_gen())));
        
        public static nethereum_gen Default {
            get {
                return defaultInstance;
            }
        }
    }
}
